name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: create output
        run: sh ./build.sh

      - name: push to personal repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.YOHAN_DEPLOY_GH_TOKEN }} # ğŸ”‘ ì‹œí¬ë¦¿ ì´ë¦„
        with:
          source-directory: "output"
          destination-github-username: ghddygks45 # â— ë„ˆ ê°œì¸ GitHub ì•„ì´ë””
          destination-repository-name: codeit-Coworkers # â— forkí•œ ê°œì¸ ë ˆí¬ ì´ë¦„
          user-email: ${{ secrets.YOHAN_GH_EMAIL }} # ğŸ“§ ì‹œí¬ë¦¿ ì´ë¦„
          commit-message: "chore: sync from team repo"
          target-branch: main
